from typing import Literal, Optional, List
from datetime import datetime
from pydantic import BaseModel, Field

# Defines the valid actions a TradePlan can execute:
# - SELL: Selling an existing position
# - BUY: Buying a new position
# - CASH_CREDIT: Recognizing cash entering the account
# - ALLOCATE_CASH: Assigning cash to a specific strategy or model
TradeActionType = Literal["SELL", "BUY", "CASH_CREDIT", "ALLOCATE_CASH"]

class TradeAction(BaseModel):
    """
    Represents a single deterministic paper execution step within a broader TradePlan.
    This defines the granular instructions that the execution engine will follow.
    """
    # The classification of the action (SELL, BUY, etc.)
    type: TradeActionType
    
    # The ticker symbol of the asset being traded (e.g., 'AAPL'), if applicable
    symbol: Optional[str] = None
    
    # The specific number of shares to trade
    shares: Optional[float] = None
    
    # The target dollar amount to trade (can be used instead of shares for fractional/dollar-based trading)
    dollars: Optional[float] = None
    
    # A generic amount, often used when neither shares nor dollars specifically apply (e.g., cash transfers)
    amount: Optional[float] = None
    
    # Identifier for the specific model or strategy that generated this recommendation
    model_key: Optional[str] = None
    
    # Optional human-readable context or reasoning for why this specific action is being taken
    notes: Optional[str] = None


class TradePlan(BaseModel):
    """
    Represents an end-to-end strategy ledger mapping an initial prompt to a list of sequential paper executions.
    This is the comprehensive "proposal" generated by the AI for a user's portfolio.
    """
    # Unique identifier for this specific trade plan
    plan_id: str
    
    # Identifier linking this plan to a broader advisory program or portfolio
    program_key: str
    
    # Timestamp of when the plan was generated
    created_at: datetime
    
    # A high-level, human-readable overview of what the entire plan achieves
    summary: str
    
    # A list of specific reasons or rationale explaining the need for this plan
    why: List[str]
    
    # The default pricing logic used to evaluate trades during simulation (ensures deterministic output)
    assumed_price_policy: str = Field(default="fixed_1.0", description="Pricing model for deterministic evaluation")
    
    # The estimated net change to the portfolio's cash balance if all actions are executed
    cash_delta_estimate: float
    
    # The chronological sequence of trades to execute this plan
    actions: List[TradeAction]
    
    # Flag indicating whether this plan requires advisor or client review before execution
    requires_approval: bool = True

class CombinedTradePlan(BaseModel):
    """
    Unified representation of a transition proposal encompassing both
    the sell-side (CP unwinds) and buy-side (MP allocations).
    """
    sell_orders: List[TradePlan]
    buy_orders: List[TradePlan]
    total_tax_estimate: float
    net_reinvestment_total: float

class TransitionRequest(BaseModel):
    """
    Input parameters for the unified transition proposal endpoint.
    """
    risk_score: int
    model_id: str
    target_dte_days: int = 30
    target_delta: float = 0.20
    share_reduction_trigger_pct: float = 0.0
    coverage_pct: float = 50.0
    loss_handling_mode: str = "harvest_hold"
    max_shares_per_month: int = 200
    starting_cash: float = 0.0
